# Generated by Django 3.2.5 on 2021-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price (in Ruppes)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight (in Kg)'),
        ),
    ]
